### ISSUE TITLE
sftp.trans.remote sending all files to remote

### ISSUE THREAD

**Issue by MarekLew** [liximomo/vscode-sftp#236] opened 2018-07-16 14:50 UTC
## Expected Behavior
sftp.trans.remote sending selected files to remote

## Actual Behavior
sftp.trans.remote sending all files to remote

## Steps to Reproduce the Problem
add to keybildings.js:
```
{
    "key": "ctrl+u",
    "command": "sftp.trans.remote",
    "when": "editorTextFocus"
},
```
When use 'ctrl+u' from current file thes transfer all files to serwer. From command is similar or the same problem. 
## Specifications

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

**Comment by MarekLew** [comment] 2018-07-16 14:54
At this moment I fixed this:

```
// selected file or activeTarget or configContext
function selectFileFallbackToConfigContext(item, items) {
    // command palette
    if (item === undefined) {
        return select_2.selectContext().then(path => ({ fsPath: path }));
    }
    // short cut
    if (item === null || !item.fsPath) {
        return getActiveTarget();
    }
    return Promise.resolve(items ? items : item);
}
```
to this:
```
// selected file or activeTarget or configContext
function selectFileFallbackToConfigContext(item, items) {
    // command palette
    if (item && item.fsPath) {
        return select_2.selectContext().then(path => ({ fsPath: path }));
    }
    // short cut
    if (item === null || item === undefined || !item.fsPath) {
        return getActiveTarget();
    }
    return Promise.resolve(items ? items : item);
}
```

but I don`t analize code.

**Comment by liximomo** [comment] 2018-07-17 06:49
duplicate of #214

**Closed by liximomo** 2018-07-17 06:49 UTC

**Comment by andremacola** [comment] 2018-07-17 12:35
the @MarekLew temp solution is working.

**Comment by MarekLew** [comment] 2018-07-17 20:53
@andremacola it is not solutuin, only destroy curent behavior.  And what I write not have sense.

**Comment by MarekLew** [comment] 2018-07-17 21:08
Beter:```
// selected file or activeTarget or configContext
function selectFileFallbackToConfigContext(item, items) {
    if (item && item.fsPath) {
            return Promise.resolve(items ? items : item);
    }
    // command palete
    // short cut
    if (item === null || item === undefined || !item.fsPath) {
        return getActiveTarget();
    }
    return select_2.selectContext().then(path => ({ fsPath: path }));
}
```
But last line not have sense and never have sense for select one file.

**Comment by MarekLew** [comment] 2018-07-18 16:01
Menu don't work

**Comment by MarekLew** [comment] 2018-07-19 08:40
Best solution, change `keybildings.js`:
```
{
    "key": "ctrl+u",
    "command": "sftp.trans.remote",
    "when": "editorTextFocus",
    "args": [null]
},
```
