### ISSUE TITLE
config file not found when already there

### ISSUE THREAD

**Issue by dylanh724** [liximomo/vscode-sftp#125] opened 2018-03-09 08:06 UTC
File is already in place using a template from your old one? It will say not found. Even if you setup config - it will bring up the existing file, yet still not recognize it.

Reproduced every time. I need to copy (back up) the file, delete the file, setup config, then paste in the values.

**Comment by liximomo** [comment] 2018-03-09 08:37
[set option `sftp.printDebugLog` to true, then reload vscode, reproduce the problem, get the logs(view -> output-> sftp)]

**Comment by dylanh724** [comment] 2018-04-06 03:05
My laptop died that day, so I ended up getting distracted from this issue. I have now reproduced this again with my new laptop after using a copy+paste hierarchy from my desktop.

How do I turn on sftp.printDebugLog?　I'm still new to VSCode.

**Comment by liximomo** [comment] 2018-04-06 03:49
Open your VSCode preference, setting `sftp.printDebugLog` to true.

**Comment by bliteknight** [comment] 2018-04-11 12:59
I had a similar issue happen to me. My  config file was set to load an ssh key over a network share that wasn't mounted; so when I tried to upload I would either get couldn't load the key error or config file not found error.

It got fixed once I mounted the share - so it could be something going on in your config file.

**Comment by clayms** [comment] 2018-04-13 19:12
Same problem in Windows 10.  

debug output
```
[info] config at o:\_Projects {"name":null,"protocol":"sftp","host":"000.000.000.000","port":22,"username":"user","password":"secret","connectTimeout":10000,"agent":null,"privateKeyPath":null,"passphrase":null,"interactiveAuth":false,"secure":false,"secureOptions":null,"passive":false,"remotePath":"./home/user/projects/","uploadOnSave":false,"downloadOnOpen":false,"syncMode":"update","ignore":[".vscode",".git",".DS_Store","__pycache__",".ropeproject"],"watcher":{"files":false,"autoUpload":false,"autoDelete":false},"concurrency":512,"context":"o:\\_Projects"}
[debug] run command upload {"$mid":1,"fsPath":"o:\\_Projects\\test.txt","external":"file:///o%3A/_Projects/test.txt","path":"/o:/_Projects/test.txt","scheme":"file"} [{"$mid":1,"fsPath":"o:\\_Projects\\test.txt","external":"file:///o%3A/_Projects/test.txt","path":"/o:/_Projects/test.txt","scheme":"file"}]
[error]: Error: (o:\_Projects\test.txt) config file not found
    at Object.getConfig (C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.7\out\src\modules\config.js:135:15)
    at FileCommand.<anonymous> (C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.7\out\src\commands\FileCommand.js:27:41)
    at Generator.next (<anonymous>)
    at C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.7\out\src\commands\FileCommand.js:7:71
    at Promise (<anonymous>)
    at __awaiter (C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.7\out\src\commands\FileCommand.js:3:12)
    at FileCommand.handleFile (C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.7\out\src\commands\FileCommand.js:24:16)
    at pendingTasks.concat.map.target (C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.7\out\src\commands\FileCommand.js:43:72)
    at Array.map (native)
    at FileCommand.<anonymous> (C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.7\out\src\commands\FileCommand.js:43:53)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.7\out\src\commands\FileCommand.js:4:58)
    at <anonymous>
```

**Comment by liximomo** [comment] 2018-04-14 01:04
@clayms Please help me test the [debug-package](https://github.com/liximomo/vscode-sftp/tree/debug-pacakge) and give me the logs.

**Comment by clayms** [comment] 2018-04-14 14:57
@liximomo ok

```
PS C:\WINDOWS\system32> code --install-extension C:\Users\user\Downloads\sftp-debug.vsix
Extension 'sftp-debug.vsix' was successfully installed!
```

**Comment by liximomo** [comment] 2018-04-14 15:01
@clayms  Using the debug version to reproduce the problem and give me the extension logs.

**Comment by clayms** [comment] 2018-04-14 15:58
yes, just had to run it and remove the personal details:


```
[debug] run command upload {"$mid":1,"fsPath":"o:\\_Projects\\test.txt","external":"file:///o%3A/_Projects/test.txt","path":"/o:/_Projects/test.txt","scheme":"file"} [{"$mid":1,"fsPath":"o:\\_Projects\\test.txt","external":"file:///o%3A/_Projects/test.txt","path":"/o:/_Projects/test.txt","scheme":"file"}]
[debug] sep: \
[debug] platform: win32
[debug] config detail: {"option":{"delimiter":"\\"},"root":{"token":"@root","value":null,"children":{"o:":{"token":"o:","value":null,"children":{"_Projects":{"token":"_Projects","value":null,"children":{"test":{"token":"test","value":null,"children":{"_LocalGitRepo":{"token":"_LocalGitRepo","value":null,"children":{"test":{"token":"test","value":null,"children":{"_LocalGitRepo":{"token":"_LocalGitRepo","value":{"name":null,"protocol":"sftp","host":"000.000.000.000","port":22,"username":"user","password":"secret","connectTimeout":10000,"agent":null,"privateKeyPath":null,"passphrase":null,"interactiveAuth":false,"secure":false,"secureOptions":null,"passive":false,"remotePath":"/home/user/projects/","uploadOnSave":true,"downloadOnOpen":false,"syncMode":"update","ignore":[".vscode",".git",".DS_Store","__pycache__",".ropeproject",".remote-sync.json"],"watcher":{"files":false,"autoUpload":false,"autoDelete":false},"concurrency":512,"context":"o:\\_Projects"},"children":{}}}}}},"test":{"token":"test","value":null,"children":{"_LocalGitRepo":{"token":"_LocalGitRepo","value":{"name":null,"protocol":"sftp","host":"000.000.000.000","port":22,"username":"user","password":"secret","connectTimeout":10000,"agent":null,"privateKeyPath":null,"passphrase":null,"interactiveAuth":false,"secure":false,"secureOptions":null,"passive":false,"remotePath":"./home/user/projects/","uploadOnSave":true,"downloadOnOpen":false,"syncMode":"update","ignore":[".vscode",".git",".DS_Store","__pycache__",".ropeproject",".remote-sync.json"],"watcher":{"files":false,"autoUpload":false,"autoDelete":false},"concurrency":512,"context":"o:\\_Projects"},"children":{}}}}}}}}}}}}}
[debug] target: o:\_Projects\test.txt
[debug] normalized target: o:\_Projects\test.txt
[debug] find config: null
[error]: Error: (o:\_Projects\test.txt) config file not found
	at Object.getConfig (C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.7\out\src\modules\config.js:141:15)
	at FileCommand.<anonymous> (C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.7\out\src\commands\FileCommand.js:27:41)
	at Generator.next (<anonymous>)
	at C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.7\out\src\commands\FileCommand.js:7:71
	at Promise (<anonymous>)
	at __awaiter (C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.7\out\src\commands\FileCommand.js:3:12)
	at FileCommand.handleFile (C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.7\out\src\commands\FileCommand.js:24:16)
	at pendingTasks.concat.map.target (C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.7\out\src\commands\FileCommand.js:43:72)
	at Array.map (native)
	at FileCommand.<anonymous> (C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.7\out\src\commands\FileCommand.js:43:53)
	at Generator.next (<anonymous>)
	at fulfilled (C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.7\out\src\commands\FileCommand.js:4:58)
	at <anonymous>
```

**Comment by liximomo** [comment] 2018-04-15 00:10
@clayms It's not the full log. I need all logs from vscode startup.

**Comment by geeeeeeeeek** [comment] 2018-04-15 03:24
The same issue occurred to me. I guess it has something to do with the vs code update.

**Comment by liximomo** [comment] 2018-04-15 03:47
@geeeeeeeeek Could provide the logs?

**Comment by clayms** [comment] 2018-04-15 18:03
@liximomo 
I still have `"sftp.printDebugLog": true` in my `USER SETTINGS`, but for some reason vsCode is not showing anything in the `OUTPUT` tab anymore.  I just recently updated to vsCode version 1.22.2.  Did that break something else?

**Comment by liximomo** [comment] 2018-04-16 10:00
No. It shouldn't break anything. Try reinstall the extension.

**Comment by clayms** [comment] 2018-04-16 15:20
ok, that worked.

Complete logs from the moment after I restarted vscode and tried to use sftp to upload a file.

Is the extension looking for the `config file` inside the file I am trying to upload?
Why is it reporting `Error: (o:\A\test.txt) config file not found` ?  Shouldn't it be looking just in `o:\A\` ?
Trying `SFTP: Upload` or `SFTP: Sync To Remote` on a folder gives the same error.

However, even trying to upload the `sftp.json` gives `Error: (o:\.vscode\sftp.json) config file not found` .

```
[info] config at o:\A\ {"name":null,"protocol":"sftp","host":"000.000.000.000","port":22,"username":"user","password":"secret","connectTimeout":10000,"agent":null,"privateKeyPath":null,"passphrase":null,"interactiveAuth":false,"secure":false,"secureOptions":null,"passive":false,"remotePath":"/home/user/projects/","uploadOnSave":true,"downloadOnOpen":false,"syncMode":"update","ignore":[".vscode",".git",".DS_Store","__pycache__",".ropeproject",".remote-sync.json"],"watcher":{"files":false,"autoUpload":false,"autoDelete":false},"concurrency":512,"context":"o:\\A"}
[info] config at o:\A\ {"name":null,"protocol":"sftp","host":"000.000.000.000","port":22,"username":"user","password":"secret","connectTimeout":10000,"agent":null,"privateKeyPath":null,"passphrase":null,"interactiveAuth":false,"secure":false,"secureOptions":null,"passive":false,"remotePath":"./home/user/projects/","uploadOnSave":true,"downloadOnOpen":false,"syncMode":"update","ignore":[".vscode",".git",".DS_Store","__pycache__",".ropeproject",".remote-sync.json"],"watcher":{"files":false,"autoUpload":false,"autoDelete":false},"concurrency":512,"context":"o:\\A\\1\\1\\1"}
[debug] sep: \
[debug] platform: win32
[debug] config detail: {"option":{"delimiter":"\\"},"root":{"token":"@root","value":null,"children":{"o:":{"token":"o:","value":null,"children":{"A":{"token":"A","value":null,"children":{"1":{"token":"1","value":null,"children":{"1":{"token":"1","value":null,"children":{"1":{"token":"1","value":null,"children":{"1":{"token":"1","value":{"name":null,"protocol":"sftp","host":"000.000.000.000","port":22,"username":"user","password":"secret","connectTimeout":10000,"agent":null,"privateKeyPath":null,"passphrase":null,"interactiveAuth":false,"secure":false,"secureOptions":null,"passive":false,"remotePath":"/home/user/projects/","uploadOnSave":true,"downloadOnOpen":false,"syncMode":"update","ignore":[".vscode",".git",".DS_Store","__pycache__",".ropeproject",".remote-sync.json"],"watcher":{"files":false,"autoUpload":false,"autoDelete":false},"concurrency":512,"context":"o:\\A"},"children":{}}}}}},"1":{"token":"1","value":null,"children":{"1":{"token":"1","value":{"name":null,"protocol":"sftp","host":"000.000.000.000","port":22,"username":"user","password":"secret","connectTimeout":10000,"agent":null,"privateKeyPath":null,"passphrase":null,"interactiveAuth":false,"secure":false,"secureOptions":null,"passive":false,"remotePath":"./home/user/projects/","uploadOnSave":true,"downloadOnOpen":false,"syncMode":"update","ignore":[".vscode",".git",".DS_Store","__pycache__",".ropeproject",".remote-sync.json"],"watcher":{"files":false,"autoUpload":false,"autoDelete":false},"concurrency":512,"context":"o:\\A\\1\\1\\1"},"children":{}}}}}}}}}}}}}
[debug] target: extension-output-#2
[debug] normalized target: extension-output-#2
[debug] find config: null
[debug] sep: \
[debug] platform: win32
[debug] config detail: {"option":{"delimiter":"\\"},"root":{"token":"@root","value":null,"children":{"o:":{"token":"o:","value":null,"children":{"A":{"token":"A","value":null,"children":{"1":{"token":"1","value":null,"children":{"1":{"token":"1","value":null,"children":{"1":{"token":"1","value":null,"children":{"1":{"token":"1","value":{"name":null,"protocol":"sftp","host":"000.000.000.000","port":22,"username":"user","password":"secret","connectTimeout":10000,"agent":null,"privateKeyPath":null,"passphrase":null,"interactiveAuth":false,"secure":false,"secureOptions":null,"passive":false,"remotePath":"/home/user/projects/","uploadOnSave":true,"downloadOnOpen":false,"syncMode":"update","ignore":[".vscode",".git",".DS_Store","__pycache__",".ropeproject",".remote-sync.json"],"watcher":{"files":false,"autoUpload":false,"autoDelete":false},"concurrency":512,"context":"o:\\A"},"children":{}}}}}},"1":{"token":"1","value":null,"children":{"1":{"token":"1","value":{"name":null,"protocol":"sftp","host":"000.000.000.000","port":22,"username":"user","password":"secret","connectTimeout":10000,"agent":null,"privateKeyPath":null,"passphrase":null,"interactiveAuth":false,"secure":false,"secureOptions":null,"passive":false,"remotePath":"./home/user/projects/","uploadOnSave":true,"downloadOnOpen":false,"syncMode":"update","ignore":[".vscode",".git",".DS_Store","__pycache__",".ropeproject",".remote-sync.json"],"watcher":{"files":false,"autoUpload":false,"autoDelete":false},"concurrency":512,"context":"o:\\A\\1\\1\\1"},"children":{}}}}}}}}}}}}}
[debug] target: o:\A\test.txt
[debug] normalized target: o:\A\test.txt
[debug] find config: null
[debug] run command upload {"$mid":1,"fsPath":"o:\\A\\test.txt","external":"file:///o%3A/A/test.txt","path":"/O:/A/test.txt","scheme":"file"} [{"$mid":1,"fsPath":"o:\\A\\test.txt","external":"file:///o%3A/A/test.txt","path":"/O:/A/test.txt","scheme":"file"}]
[debug] sep: \
[debug] platform: win32
[debug] config detail: {"option":{"delimiter":"\\"},"root":{"token":"@root","value":null,"children":{"o:":{"token":"o:","value":null,"children":{"A":{"token":"A","value":null,"children":{"1":{"token":"1","value":null,"children":{"1":{"token":"1","value":null,"children":{"1":{"token":"1","value":null,"children":{"1":{"token":"1","value":{"name":null,"protocol":"sftp","host":"000.000.000.000","port":22,"username":"user","password":"secret","connectTimeout":10000,"agent":null,"privateKeyPath":null,"passphrase":null,"interactiveAuth":false,"secure":false,"secureOptions":null,"passive":false,"remotePath":"/home/user/projects/","uploadOnSave":true,"downloadOnOpen":false,"syncMode":"update","ignore":[".vscode",".git",".DS_Store","__pycache__",".ropeproject",".remote-sync.json"],"watcher":{"files":false,"autoUpload":false,"autoDelete":false},"concurrency":512,"context":"o:\\A"},"children":{}}}}}},"1":{"token":"1","value":null,"children":{"1":{"token":"1","value":{"name":null,"protocol":"sftp","host":"000.000.000.000","port":22,"username":"user","password":"secret","connectTimeout":10000,"agent":null,"privateKeyPath":null,"passphrase":null,"interactiveAuth":false,"secure":false,"secureOptions":null,"passive":false,"remotePath":"./home/user/projects/","uploadOnSave":true,"downloadOnOpen":false,"syncMode":"update","ignore":[".vscode",".git",".DS_Store","__pycache__",".ropeproject",".remote-sync.json"],"watcher":{"files":false,"autoUpload":false,"autoDelete":false},"concurrency":512,"context":"o:\\A\\1\\1\\1"},"children":{}}}}}}}}}}}}}
[debug] target: o:\A\test.txt
[debug] normalized target: o:\A\test.txt
[debug] find config: null
[error]: Error: (o:\A\test.txt) config file not found
	at Object.getConfig (C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.7\out\src\modules\config.js:141:15)
	at FileCommand.<anonymous> (C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.7\out\src\commands\FileCommand.js:27:41)
	at Generator.next (<anonymous>)
	at C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.7\out\src\commands\FileCommand.js:7:71
	at Promise (<anonymous>)
	at __awaiter (C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.7\out\src\commands\FileCommand.js:3:12)
	at FileCommand.handleFile (C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.7\out\src\commands\FileCommand.js:24:16)
	at pendingTasks.concat.map.target (C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.7\out\src\commands\FileCommand.js:43:72)
	at Array.map (native)
	at FileCommand.<anonymous> (C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.7\out\src\commands\FileCommand.js:43:53)
	at Generator.next (<anonymous>)
	at fulfilled (C:\Users\user\.vscode\extensions\liximomo.sftp-1.1.7\out\src\commands\FileCommand.js:4:58)
	at <anonymous>
```

**Comment by liximomo** [comment] 2018-04-17 01:40
The content you set is `o:\\A\\1\\1\\1`. Then you can only upload files under `o:\\A\\1\\1\\1` directory!

**Comment by clayms** [comment] 2018-04-17 11:25
That is just from me editing personal details out of the log file and not the cause of the problem.  The problem appears to have been caused by having both child and parent directories added to the workspace, and sftp seeing the sftp.json file twice.  I removed the parent directory from the workspace, as the child was the one I was working in, and the problem went away.

**Closed** 2018-08-06 09:44 UTC
