### ISSUE TITLE
During uploadOnSave, files in "ignored" directories are still uploaded

### ISSUE THREAD

**Issue by duanehutchins** [liximomo/vscode-sftp#15] opened 2017-07-21 12:32 UTC
Issue: 

During `uploadOnSave`, files in "ignored" directories are still uploaded on save. In other words, the 'ignore' setting is not respected for directories during `uploadOnSave`.

Relevant Settings: 
```
{
    ...
    "uploadOnSave": true,
    "ignore": [
        "**/ignoreme"
    ]
}
```

Steps to duplicate:
- [ ] Create new directory `ignoreme/`
- [ ] Create a new file `ignoreme/myfile.txt`
- [ ] Set `uploadOnSave` to `true` 
- [ ] Add `**/ignoreme` to the `ignore` list.
- [ ] Change `ignoreme/myfile.txt` and save.
- [ ] Note that `ignoreme/myfile.txt` is uploaded to the server, even though `ignoreme/` is an ignored folder.

What should happen:
* Files in "ignored" directories should not upload, even during uploadOnSave.

Please fix this. It is very annoying. It causes my local `.git/` files to upload to the server.

**Comment by liximomo** [comment] 2017-07-22 06:30
Please change you vscode setting option `sftp.printDebugLog` to true and provide me the full log(view -> output-> sftp).

**Comment by duanehutchins** [comment] 2017-07-23 04:27
I will get this for you on Monday.

**Comment by tomjaimz** [comment] 2017-07-23 08:50
@duanehutchins To match ignored files, sftp tries both the glob-enhanced/regular expression matching tool `minimatch`, and also a more standardised `indexOf` direct string match.

The suggested config for ignore gives paths that will not work adequately in either of these scenarios.  They are prefixed with the glob `**` which will match the parent of the desired directory, but have no matching criteria for any files or directories within.

In your current scenario the easiest thing to do in the short term is to fall back on the standard `indexOf` matching, and use `/ignoreme` instead of `**/ignoreme` (or specifically, `/.git/`).

You could optionally chose to provide a more comprehensive pattern with a suffix glob, in the form of `**/ignoreme/**`, however this could likely expose a bug in @liximomo's code, that he is not overriding the default behaviour of `minimatch`, which will automatically not match global operators if the string they would match contains a dot file (so `/ignoreme/.file`) would not be ignored.

@liximomo - to address this, I suggest complementing your call to minimatch in conveyer.js so that instead of `minimatch(target, pattern)` it is `minimatch(target, pattern, { dot: true })`.

**Comment by liximomo** [comment] 2017-07-24 06:11
@tomjaimz Thanks for your help! I will take your advice.

**Comment by duanehutchins** [comment] 2017-07-24 13:10
Thanks @liximomo for looking at this, and thanks @tomjaimz for your help.

Here's the debug log output for sftp:
```
config at @workroot {
    "host": "web01",
    "port": 22,
    "username": "drh",
    "password": null,
    "protocol": "sftp",
    "agent": null,
    "privateKeyPath": "C:\\Users\\drh\\.ssh\\privatekey.ppk",
    "passphrase": null,
    "passive": false,
    "interactiveAuth": false,
    "remotePath": "./public_html/myinventory",
    "uploadOnSave": true,
    "syncMode": "update",
    "watcher": {
        "files": false,
        "autoUpload": false,
        "autoDelete": false
    },
    "ignore": [
        "c:/Users/drh/WebDocs/myinventory/**/.vscode",
        "c:/Users/drh/WebDocs/myinventory/**/.git",
        "c:/Users/drh/WebDocs/myinventory/**/.DS_Store",
        "c:/Users/drh/WebDocs/myinventory/.htaccess",
        "c:/Users/drh/WebDocs/myinventory/index.cgi",
        "c:/Users/drh/WebDocs/myinventory/invoice_pdfs",
        "c:/Users/drh/WebDocs/myinventory/jobpdfs",
        "c:/Users/drh/WebDocs/myinventory/pdfs",
        "c:/Users/drh/WebDocs/myinventory/materialimages/proofs",
        "public_html/myinventory/**/.vscode",
        "public_html/myinventory/**/.git",
        "public_html/myinventory/**/.DS_Store",
        "public_html/myinventory/.htaccess",
        "public_html/myinventory/index.cgi",
        "public_html/myinventory/invoice_pdfs",
        "public_html/myinventory/jobpdfs",
        "public_html/myinventory/pdfs",
        "public_html/myinventory/materialimages/proofs"
    ],
    "configRoot": "c:/Users/drh/WebDocs/myinventory"
}
```

Using the ignore pattern of `**/.git/**` works, but then causes another issue. When I ignore that pattern and keep `uploadOnSave` true, then I get a message in vscode on the bottom-left stating: `retriving directory .git`

![image](https://user-images.githubusercontent.com/1530028/28524275-cec22516-704d-11e7-8aa0-e6c1e7c4a8f4.png)

This message doesn't go away.  Well, sometimes it goes away, but then it comes back, and my CPU usage for vscode goes up a bit.

**Comment by duanehutchins** [comment] 2017-07-24 14:38
Update: The issue with setting ignore `**/.git/**` may actually be causing a memory leak.

By using that setting and simply leaving my vscode open, unused, vscode memory usage climbs steadily at a rate of about 10kb per minute.  This does not happen without that setting.

**Comment by liximomo** [comment] 2017-07-25 03:22
`**/.git/**` means every file under .git but not include .git folder itself, which cause necessary retrieval of .git folder. I will fix the counter-intuitive behavior.

**Comment by BMannell** [comment] 2017-07-25 18:53
I am not seeing any memory leakage using `**/.git/**`. I will keep an eye on it though.

**Comment by jessemao** [comment] 2017-09-08 07:20
I am trying to ignore `node_modules` and tried `**/node_modules/**`, `/node_modules`, `/node_modules/**`, none of them works, need help!

**Comment by liximomo** [comment] 2017-09-08 08:32
@jessemao Get me the logs.
Set option sftp.printDebugLog to true, then reload vscode, reproduce the problem, get the logs(view -> output-> sftp)

**Comment by liximomo** [comment] 2018-01-26 05:24
Since how the ignore works changed after `v1.0.0`,  so I'm close this.

**Closed** 2018-01-26 05:25 UTC

**Comment by tom-tom-cp** [comment] 2018-02-23 13:18
Hey liximomo. I'm having the exact same issue, I can't get the package to ignore anything other than the .vscode folder where the config is in. I think it was working properly some time ago. I've been testing some variations of the config, none works. I've tried multiple patterns for the ignore array but nothing seems to work. 

Anyway here's my output:

[info]: config at /Users/** {
    "protocol": "sftp",
    "host": "foo.bar",
    "port": 22,
    "username": "username",
    "password": "***********",
    "agent": null,
    "privateKeyPath": null,
    "passphrase": null,
    "interactiveAuth": false,
    "secure": false,
    "secureOptions": null,
    "passive": false,
    "remotePath": "/foo.bar",
    "uploadOnSave": true,
    "syncMode": "update",
    "ignore": [
        "**/.vscode/**",
        "**/.DS_Store/**",
        "project_details.txt",
        ".eslintrc.json",
        "**/node_modules/**",
        "**/.git/**"
    ],
    "watcher": {
        "files": false,
        "autoUpload": false,
        "autoDelete": false
    },
    "concurrency": 512,
    "context": "/Users/**"
}

Thanks in advance.

**Comment by liximomo** [comment] 2018-02-24 03:10
Change to this and provide me the log if it still can't work.
```
"ignore": [
        ".vscode",
        ".DS_Store",
        "project_details.txt",
        ".eslintrc.json",
        "node_modules",
        ".git"
]
```

**Comment by tom-tom-cp** [comment] 2018-02-24 10:23
Working now thanks a lot.

**Comment by joerimarquerinck** [comment] 2018-08-17 07:06
Hi,

This issue is the one I am having where I have a local folder structure that is having the folders /assets/styles/ and then several .scss files (also within folder like /pages/, /components/. I would like to ignore this entire /assets/styles/ folder or every .scss file. I have tried several things but nothing is ignoring these files.

What's the correct way of ignoring files within subfolders or entire subfolders?

**Comment by EFXPROMedia** [comment] 2018-12-12 17:22
This is not working for subdirectories /folder/subfolders/
