### ISSUE TITLE
Why can't this plugin use SSH_AUTH_SOCK env variable?

### ISSUE THREAD

**Issue by xornet-sl** [liximomo/vscode-sftp#261] opened 2018-07-27 16:31 UTC
## Expected Behavior
I have an ssh agent started on my localhost (Linux), so there is env variable SSH_AUTH_SOCK, which is pointing to current valid ssh agent sockt. Plugin is supposed to use this well-known ENV variable!

## Actual Behavior
Now I have to write stupid wrapper around ssh-agent to create symbolic link to actual auth socket. If I hadn't done this I would change sftp.json every time I restart my computer.
My private key is encrypted and there is no password authentication on remote host, so only authentication via ssh agent is suitable for me.

## Specifications

  - Version: 1.2.8
  - Platform: vscode 1.25.1 on Linux Arch (recently updated)

**Comment by liximomo** [comment] 2018-07-28 01:54
Duplicate of #18 
```
"agent": "$SSH_AUTH_SOCK"
```

**Closed by liximomo** 2018-07-28 01:54 UTC
