### ISSUE TITLE
There aren't a way to set update more than one online file?

### ISSUE THREAD

**Issue by giovanenogit** [liximomo/vscode-sftp#636] opened 2019-08-29 20:44 UTC
I'm setting the config to work with two ( or more in future ) sites online. So I wanna upload them automatically ( with autoUpload ).

I tried like this in sftp.json :

```
[
    {
        "name": "name123",
        "host": "host123",
        "protocol": "ftp",
        "uploadOnSave": true,
        "port": 21,
        "username": "user123",
        "password": "pass123",
        "watcher": {
            "files": "dist/*.{js,css}",
            "autoUpload": true,
            "autoDelete": false
            },
        "remotePath": "/public_html"
    },
    {
        "name": "name666",
        "host": "host66",
        "protocol": "ftp",
        "context": "/project/build3",
        "uploadOnSave": true,
        "port": 21,
        "username": "user666",
        "password": "pass666",
        "watcher": {
            "files": "dist/*.{js,css}",
            "autoUpload": true,
            "autoDelete": false
          },
        "remotePath": "/public_html"
    },
    {
        "name": "name3",
        "host": "host3",
        "protocol": "ftp",
        "uploadOnSave": true,
        "port": 21,
        "username": "user3",
        "password": "pass3",
        "watcher": {
            "files": "dist/*.{js,css}",
            "autoUpload": true,
            "autoDelete": false
          },
        "remotePath": "/public_html"
    }
]
```
But the name123 just disappear from my folders list. Can't I have two or more sites on updateAuto online?

**Comment by liximomo** [comment] 2019-09-17 04:10
Duplicate of #107

**Closed by liximomo** 2019-09-17 04:10 UTC
