### ISSUE TITLE
Sync to Remote: "Cannot read property 'substr' of undefined"

### ISSUE THREAD

**Issue by mitchp** [liximomo/vscode-sftp#246] opened 2018-07-20 04:31 UTC
## Expected Behavior
If I select a folder (directory) in the file explorer and execute sftp: Sync to Remote, it should sync the directory

## Actual Behavior
I get the following error: Cannot read property 'substr' of undefined

## Steps to Reproduce the Problem

  1. Select a directory(folder) in the explorer panel
  1. Right-click and select sftp: Sync to Remote from context Menu
  1. See error messate

### Extension Logs

>  [info] config at d:\webdev\KahalChasidim {"name":"Kahal Chasidim Main Site","protocol":"sftp","host":"kahalchasidim.com","port":22,"username":"******","password":"******","connectTimeout":10000,"interactiveAuth":false,"sshConfigPath":"~/.ssh/config","secure":false,"passive":false,"remotePath":"/kahalcha/public_html","uploadOnSave":false,"downloadOnOpen":false,"syncMode":"update","ignore":["**/.vscode/**","**/.git/**","**/.DS_Store","**/.code-workspace"],"watcher":{"files":false,"autoUpload":false,"autoDelete":false},"concurrency":4,"context":"d:\\webdev\\KahalChasidim"}
> [info] config at d:\htdocs\kahalcha {"name":"Kahal Chasidim Main Site","protocol":"sftp","host":"kahalchasidim.com","port":22,"username":"******","password":"******","connectTimeout":10000,"interactiveAuth":false,"sshConfigPath":"~/.ssh/config","secure":false,"passive":false,"remotePath":"/home/kahalcha/public_html/","uploadOnSave":false,"downloadOnOpen":false,"syncMode":"update","ignore":["**/.vscode/**","**/.git/**","**/.DS_Store","**/.code-workspace"],"watcher":{"files":false,"autoUpload":false,"autoDelete":false},"concurrency":4,"context":"d:\\htdocs\\kahalcha"}
> [error] TypeError: Cannot read property 'toString' of undefined
>    at args.map.arg (C:\Users\mitch\.vscode\extensions\liximomo.sftp-1.2.5\out\src\ui\output.js:32:22)
>    at Array.map (native)
>    at Object.print (C:\Users\mitch\.vscode\extensions\liximomo.sftp-1.2.5\out\src\ui\output.js:28:10)
>   at VSCodeLogger.trace (C:\Users\mitch\.vscode\extensions\liximomo.sftp-1.2.5\out\src\logger.js:10:20)
>   at FileCommand.<anonymous> (C:\Users\mitch\.vscode\extensions\liximomo.sftp-1.2.5\out\src\commands\FileCommand.js:35:30)
>   at Generator.next (<anonymous>)
>   at C:\Users\mitch\.vscode\extensions\liximomo.sftp-1.2.5\out\src\commands\FileCommand.js:7:71
>   at Promise (<anonymous>)
>   at __awaiter (C:\Users\mitch\.vscode\extensions\liximomo.sftp-1.2.5\out\src\commands\FileCommand.js:3:12)
>   at FileCommand.handleFile (C:\Users\mitch\.vscode\extensions\liximomo.sftp-1.2.5\out\src\commands\FileCommand.js:33:16)
>   at pendingTasks.concat.map.target (C:\Users\mitch\.vscode\extensions\liximomo.sftp-1.2.5\out\src\commands\FileCommand.js:55:72)
>   at Array.map (native)
>   at FileCommand.<anonymous> (C:\Users\mitch\.vscode\extensions\liximomo.sftp-1.2.5\out\src\commands\FileCommand.js:55:53)
>   at Generator.next (<anonymous>)
>   at fulfilled (C:\Users\mitch\.vscode\extensions\liximomo.sftp-1.2.5\out\src\commands\FileCommand.js:4:58)
>   at <anonymous>

## Specifications

  - Version: SFTP v 1.2.5
  - Platform: VS Code:
<pre>
Version: 1.25.1
Commit: 1dfc5e557209371715f655691b1235b6b26a06be
Date: 2018-07-11T15:43:53.668Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64
</pre>

**Comment by liximomo** [comment] 2018-07-20 07:35
Duplicate of  #220

**Closed by liximomo** 2018-07-20 07:35 UTC
