### ISSUE TITLE
 How to solve the "multi-config feature will be deprecated" warning?

### ISSUE THREAD

**Issue by yangcore** [liximomo/vscode-sftp#59] opened 2017-11-19 15:31 UTC
[sftp]: You have a config file not located in workspace root folder. This multi-config feature will be deprecated next update for better performance.

use 'vscode ' multi-root workspace, How do I configure? 

Give an example?

thank you!

**Comment by liximomo** [comment] 2017-11-20 01:31
Suppose you've opened a folder 'project' with vscode.
```
/project  // workspace root folder
  |- .vscode/sftp.json  - you should create sftp.json in here.
  |- somefolderA
     |- .vscode/sftp.json // none worksapce root config, cause you have the waring
```

With `multi-root` feature, you could open multiple folders as workspace root folder.
```
/project  // workspace root folder
  |- .vscode/sftp.json // fine
/project/somefolderA  // workspace root folder
  |- .vscode/sftp.json  // fine
```

**Comment by yangcore** [comment] 2017-11-20 02:14
Oh, I probably know what you mean

I've used the multi-root features of vscode
But now my directory is this， So I want to work in a sub folder can create a number of different sftp.json
like this :
```
  /project/somefolderA  // workspace root folder
     |- .vscode/sftp.json //  to test
     |-XXX
       |-XXX
          |-dist
             |- .vscode/stp.json //  to production
  /project/somefolderB  // workspace root folder
     |- .vscode/sftp.json  //  to test
     |-XXX
       |-XXX
          |-dist
             |- .vscode/stp.json //  to production
```
How do I configure?
thank you!

**Comment by liximomo** [comment] 2017-11-20 02:16
```
  /project/somefolderA  // workspace root folder
     |- .vscode/sftp.json //  to test
     |-XXX
       |-XXX
          |-dist
             |- .vscode/stp.json //  to production
  /project/somefolderA/XXX/XXX/dist/ make this folder as a root folder
      |- .vscode/stp.json //  to production
  /project/somefolderB  // workspace root folder
     |- .vscode/sftp.json  //  to test
     |-XXX
       |-XXX
          |-dist
             |- .vscode/stp.json //  to production
/project/somefolderB/XXX/XXX/dist/ make this folder as a root folder
      |- .vscode/stp.json //  to production
```

**Comment by yangcore** [comment] 2017-11-20 02:30
For me, the configuration you give is inconvenient, I need to build several root-folder, I hope the "multi-config feature" do not give up, because this greatly reduces the degree of freedom of configuration, you can give a switch, allowing users to open freely

**Comment by liximomo** [comment] 2017-11-20 02:48
Because of 'multi-root', the total files of a workspace will be incredibly large. The config retrieval will have a huge performance burden. I'm now considering a new way to enable multiple configs in a single config file.

**Comment by mirino83** [comment] 2017-11-20 07:04
Same issue, not satisfied with the configuration given,
very sad about this "multi-config feature will be deprecated" news,
I use the extension a lot ....

**Comment by liximomo** [comment] 2017-11-20 08:21
@mirino83 There actually no feature is missing, just exist in another form.

**Comment by mirino83** [comment] 2017-11-20 08:27
Yes, but in inconvenient form, please do consider the "new way to enable multiple configs in a single config file"

**Comment by liximomo** [comment] 2017-12-16 09:20
@mirino83 @yangcore  Check the new way to use [multiple configs](https://github.com/liximomo/vscode-sftp#config) with 0.9.0!

**Comment by mirino83** [comment] 2017-12-16 12:26
@liximomo Great news, but i am having issues:

1. I moved sftp.json to the root .vscode folder
2. Tried to upload a file and the file was uploaded, wrong destination folder, but uploaded
3. When I added the new "context" param to resolve the right local folder, I got this error:

_[sftp] (c:\Users\xxx\xxx\project_root\xxx\css\style.css) config file not found_

Console log:
_/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2744 [sftp] (c:\Users\xxx\xxx\project_root\xxx\css\style.css) config file not found_

I also tried to create a new default sftp.json, same issue if I add the context param

my VSCODE
Version 1.19.0
Commit 816be6780ca8bd0ab80314e11478c48c70d09383
Date 2017-12-14T12:06:43.492Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Thx

**Comment by liximomo** [comment] 2017-12-16 12:53
Please provide your config. I think it's just a
 problem of config.

**Comment by mirino83** [comment] 2017-12-16 13:03
{
        "context": "/ftpfolder", // also tried "c:\\users\\mirino83\\project_root\\ftpfolder"
        "host": "ftp.project.net",
        "port": 21,
        "username": "username",
        "password": "password",
        "protocol": "ftp",
        "agent": null,
        "privateKeyPath": null,
        "passphrase": null,
        "passive": false,
        "interactiveAuth": false,
        "remotePath": "/server1/test/ftpfolder/",
        "uploadOnSave": true,
        "syncMode": "update",
        "watcher": {
            "files": false,
            "autoUpload": false,
            "autoDelete": false
        },
        "ignore": [
            "**/.vscode/**",
            "**/.git/**",
            "**/.DS_Store"
        ]
}

**Comment by liximomo** [comment] 2017-12-16 13:10
I think it's should be c:\\xx\\xx

**Comment by liximomo** [comment] 2017-12-16 13:18
Set `context` to `c:\\users\\mirino83\\project_root\\ftpfolder` and give me full log of the extension.

**Comment by mirino83** [comment] 2017-12-16 13:28
Ok, I tried:

- "c:\\users\\mirino83\\project_root\\ftpfolder"
- "\\project_root\\ftpfolder"
- "\\ftpfolder"
- "/project_root/ftpfolder"
- "/ftpfolder"

It seems that whatever I try I got the same error

extension log for c:\\users\\mirino83\\project_root\\ftpfolder:

`[info]: config at C:/Users/mirino83/project_root/ftpfolder/ {
    "host": "ftp.project.net",
    "port": 21,
    "username": "username",
    "password": "password",
    "protocol": "ftp",
    "agent": null,
    "privateKeyPath": null,
    "passphrase": null,
    "passive": false,
    "interactiveAuth": false,
    "remotePath": "/server1/test/ftpfolder/",
    "uploadOnSave": true,
    "syncMode": "update",
    "watcher": {
        "files": false,
        "autoUpload": false,
        "autoDelete": false
    },
    "ignore": [
        "C:/Users/mirino83/project_root/ftpfolder/**/.vscode/**",
        "C:/Users/mirino83/project_root/ftpfolder/**/.git/**",
        "C:/Users/mirino83/project_root/ftpfolder/**/.DS_Store",
        "/server1/test/ftpfolder/**/.vscode/**",
        "/server1/test/ftpfolder/**/.git/**",
        "/server1/test/ftpfolder/**/.DS_Store"
    ],
    "context": "C:/Users/mirino83/project_root/ftpfolder/"
}
[error]: context: undefined reason: Error: (C:\Users\mirino83\project_root\ftpfolder\css\style.css) config file not found
	at runTask (C:\Users\mirino83\.vscode\extensions\liximomo.sftp-0.9.2\out\src\helper\createCommand.js:13:19)
	at Array.forEach (native)
	at runTasks (C:\Users\mirino83\.vscode\extensions\liximomo.sftp-0.9.2\out\src\helper\createCommand.js:16:52)
	at getTarget.then.target (C:\Users\mirino83\.vscode\extensions\liximomo.sftp-0.9.2\out\src\helper\createCommand.js:22:9)
	at <anonymous>`

**Comment by liximomo** [comment] 2017-12-16 13:34
Ok. I’ve known the issue. It's should be the last
`/` at the `C:/Users/mirino83/project_root/ftpfolder/`. Please wait the fix.

**Comment by liximomo** [comment] 2017-12-16 14:17
Can you confirm that what you set is `c:\\users\\mirino83\\project_root\\ftpfolder` but not `c:\\users\\mirino83\\project_root\\ftpfolder\\`

**Comment by mirino83** [comment] 2017-12-16 14:46
you are totally right, I gave you wrong log, very very sorry about that!

this is the extension log for `c:\\users\\mirino83\\project_root\\ftpfolder`: (no `\\` at the end)

```
[info]: config at C:/Users/mirino83/project_root/ftpfolder {
    "host": "ftp.project.net",
    "port": 21,
    "username": "username",
    "password": "password",
    "protocol": "ftp",
    "agent": null,
    "privateKeyPath": null,
    "passphrase": null,
    "passive": false,
    "interactiveAuth": false,
    "remotePath": "/server1/test/ftpfolder",
    "uploadOnSave": true,
    "syncMode": "update",
    "watcher": {
        "files": false,
        "autoUpload": false,
        "autoDelete": false
    },
    "ignore": [
        "C:/Users/mirino83/project_root/ftpfolder/**/.vscode/**",
        "C:/Users/mirino83/project_root/ftpfolder/**/.git/**",
        "C:/Users/mirino83/project_root/ftpfolder/**/.DS_Store",
        "/server1/test/ftpfolder/**/.vscode/**",
        "/server1/test/ftpfolder/**/.git/**",
        "/server1/test/ftpfolder/**/.DS_Store"
    ],
    "context": "C:/Users/mirino83/project_root/ftpfolder"
}
[error]: context: undefined reason: Error: (c:\Users\mirino83\project_root\ftpfolder\css\style.css) config file not found
	at runTask (C:\Users\mirino83\.vscode\extensions\liximomo.sftp-0.9.2\out\src\helper\createCommand.js:13:19)
	at Array.forEach (native)
	at runTasks (C:\Users\mirino83\.vscode\extensions\liximomo.sftp-0.9.2\out\src\helper\createCommand.js:16:52)
	at getTarget.then.target (C:\Users\mirino83\.vscode\extensions\liximomo.sftp-0.9.2\out\src\helper\createCommand.js:22:9)
	at <anonymous>
```

it must be something else, I am trying to console log (hard coded in js files) some variables in your code and find something

**Comment by mirino83** [comment] 2017-12-16 15:41
I found this:

in file **config.js** 
- `remotePath_1.normalize(activityPath)` returns `c:/Users/mirino83/project_root/ftpfolder/css/style.css`
- `configTrie.findPrefix("c:/Users/mirino83/project_root/ftpfolder/css/style.css")` returns `null`
```
function getConfig(activityPath) {
    const config = configTrie.findPrefix(remotePath_1.normalize(activityPath));
    console.log('config', config);
    // config is null
    if (!config) {
        throw new Error('config file not found');
    }
    return Object.assign({}, config, { remotePath: getRemotePath(config, activityPath) });
}
```

**Comment by liximomo** [comment] 2017-12-16 15:57
The problem is what you set is ` C:/Users/mirino83/project_root/ftpfolder`,  but what vscode gives me is `C:\\users\\mirino83\\project_root\\ftpfolder`. Tha case of the drive letter is not matched!

**Comment by liximomo** [comment] 2017-12-16 16:02
Change `C:\\users\\mirino83\\project_root\\ftpfolder` to `c:\\users\\mirino83\\project_root\\ftpfolder` see if this worked?

**Comment by mirino83** [comment] 2017-12-16 16:08
Nope.

**Comment by liximomo** [comment] 2017-12-16 16:13
Try [debug-pacakge](https://github.com/liximomo/vscode-sftp/tree/debug-pacakge). If it fails, Please send me the logs.

**Comment by mirino83** [comment] 2017-12-16 16:44
OK, how it works? cause I installed it, restarted and it gave the same log as above, do I need to turn in on somehow?

**Comment by mirino83** [comment] 2017-12-16 16:46
I am going to try it on Linux, if it still fails ...

**Comment by liximomo** [comment] 2017-12-16 17:03
It's still output the `[info]: config at C:/Users/mirino83/project_root/ftpfolder` with upppercase 'C:'?

**Comment by liximomo** [comment] 2017-12-16 17:05
Please give me the log.

**Comment by liximomo** [comment] 2017-12-16 17:05
I've tested it. It works well both on win and mac.

**Comment by mirino83** [comment] 2017-12-16 17:12
```
[info]: config at c:/users/mirino83/project_root/ftpfolder {
    "host": "ftp.project.net",
    "port": 21,
    "username": "username",
    "password": "password",
    "protocol": "ftp",
    "agent": null,
    "privateKeyPath": null,
    "passphrase": null,
    "passive": false,
    "interactiveAuth": false,
    "remotePath": "/server1/test/ftpfolder",
    "uploadOnSave": true,
    "syncMode": "update",
    "watcher": {
        "files": false,
        "autoUpload": false,
        "autoDelete": false
    },
    "ignore": [
        "c:/users/mirino83/project_root/ftpfolder/**/.vscode/**",
        "c:/users/mirino83/project_root/ftpfolder/**/.git/**",
        "c:/users/mirino83/project_root/ftpfolder/**/.DS_Store",
        "/server1/test/ftpfolder/**/.vscode/**",
        "/server1/test/ftpfolder/**/.git/**",
        "/server1/test/ftpfolder/**/.DS_Store"
    ],
    "context": "c:/users/mirino83/project_root/ftpfolder"
}
[error]: context: undefined reason: Error: (c:\Users\mirino83\project_root\ftpfolder\css\style.css) config file not found
	at runTask (C:\Users\mirino83\.vscode\extensions\liximomo.sftp-0.9.3\out\src\helper\createCommand.js:13:19)
	at Array.forEach (native)
	at runTasks (C:\Users\mirino83\.vscode\extensions\liximomo.sftp-0.9.3\out\src\helper\createCommand.js:16:52)
	at getTarget.then.target (C:\Users\mirino83\.vscode\extensions\liximomo.sftp-0.9.3\out\src\helper\createCommand.js:22:9)
	at <anonymous>
```

**Comment by liximomo** [comment] 2017-12-16 17:15
It says `(c:\Users\mirino83\project_root\ftpfolder\css\style.css) config file not found`. I think you shuold set your context to `c:\\Users\\mirino83\\project_root\\ftpfolder`, not`c:\\users\\mirino83\\project_root\\ftpfolder`

**Comment by mirino83** [comment] 2017-12-16 17:39
You are right, the drive letter was a problem, now it works! you are the best

One tiny thing, is it really necessary to provide the absolute path? our team git the .vscode root folder with this sftp.json file  and each of us has different local path to the project, it is possible to use relative path?

**Comment by yangcore** [comment] 2017-12-18 02:43
I'm sorry, but I just saw that I tried to use the new extension. It worked. I looked at the previous problem. It seemed that I could only use absolute path. I try to use the relative path, which gives an error message ( config file not found) Can I only use absolute path? it is possible to use relative path?

**Comment by liximomo** [comment] 2017-12-18 12:05
@yangcore @mirino83 You could use a relative path since 0.9.4.

**Closed** 2017-12-19 01:13 UTC
