### ISSUE TITLE
TypeError: Cannot read property 'toString' of undefined when using context menu download of subfolder

### ISSUE THREAD

**Issue by ragokin** [liximomo/vscode-sftp#234] opened 2018-07-12 19:38 UTC
## Expected Behavior
Context menu downloads a single subfolder of a project

## Actual Behavior
Context menu fails to download anything. Error Occurs.

## Steps to Reproduce the Problem

TypeError occuring when attempting to download a single subfolder via Context menu

1. in the Workspace Explorer right click on a subfolder of your project
2. Choose either "Sync To Local" or "Download to Local" (Or upload to)
3. The following error appears in the VSCode OUTPUT terminal tab :

running ctrl-shift-p SFTP: Download works on the whole project.

### Extension Logs
[error] TypeError: Cannot read property 'toString' of undefined
	at args.map.arg (C:\Users\Alex\.vscode\extensions\liximomo.sftp-1.2.3\out\src\ui\output.js:32:22)
	at Array.map (native)
	at Object.print (C:\Users\Alex\.vscode\extensions\liximomo.sftp-1.2.3\out\src\ui\output.js:28:10)
	at VSCodeLogger.trace (C:\Users\Alex\.vscode\extensions\liximomo.sftp-1.2.3\out\src\logger.js:10:20)
	at FileCommand.<anonymous> (C:\Users\Alex\.vscode\extensions\liximomo.sftp-1.2.3\out\src\commands\FileCommand.js:35:30)
	at Generator.next (<anonymous>)
	at C:\Users\Alex\.vscode\extensions\liximomo.sftp-1.2.3\out\src\commands\FileCommand.js:7:71
	at Promise (<anonymous>)
	at __awaiter (C:\Users\Alex\.vscode\extensions\liximomo.sftp-1.2.3\out\src\commands\FileCommand.js:3:12)
	at FileCommand.handleFile (C:\Users\Alex\.vscode\extensions\liximomo.sftp-1.2.3\out\src\commands\FileCommand.js:33:16)
	at pendingTasks.concat.map.target (C:\Users\Alex\.vscode\extensions\liximomo.sftp-1.2.3\out\src\commands\FileCommand.js:54:72)
	at Array.map (native)
	at FileCommand.<anonymous> (C:\Users\Alex\.vscode\extensions\liximomo.sftp-1.2.3\out\src\commands\FileCommand.js:54:53)
	at Generator.next (<anonymous>)
	at fulfilled (C:\Users\Alex\.vscode\extensions\liximomo.sftp-1.2.3\out\src\commands\FileCommand.js:4:58)
	at <anonymous>

## Specifications

  - Version: VSCode 1.25.0 sftp 1.2.3
  - Platform: Windows 10

**Comment by ragokin** [comment] 2018-07-13 03:01
As in #220 i have the custom title bar option on. Will check in morning if disabling this solves the issue

**Comment by ragokin** [comment] 2018-07-13 11:49
Can confirm that as in #220 "window.titleBarStyle": "custom" causes the context menu's to not function for SFTP 1.2.3, with defaults SFTP functions as before.

I'll leave this open as the error trace is a bit different than the one in #220

**Comment by McNuggetSauce** [comment] 2018-07-15 23:55
@ragokin does upload on save work for you when window.titleBarStyle is set to "native" (default setting)?

i'm using a custom keybind with "sftp.trans.remote" but every time it invokes it brings up the same context menu as if the command is executed from the command palette. it works fine in 1.24 though.

**Comment by liximomo** [comment] 2018-07-16 01:57
Duplicate of #220 .

**Closed by liximomo** 2018-07-16 01:57 UTC

**Comment by ragokin** [comment] 2018-07-16 02:11
@McNuggetSauce yes. Upload on save works with both custom and native. Custom appears to break interactions only with the context menu for me. Now that i have it back on native the extension works fine.
